# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
    port: 8080
    servlet:
        context-path: /smartEdu


spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://47.111.15.15:3306/edu_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password: zhenghanyu

    mail:
      host: smtp.qq.com
      port: 465
      username: 2469835322@qq.com
      password: auxtddwqezwgeaei
      properties:
        mail:
          smtp:
            auth: true
            ssl:
              enable: true  # QQ邮箱使用SSL加密



  #        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#        url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=springbootsagm21hd
#        username: sa
#        password: 123456

    servlet:
      multipart:
        max-file-size: 5GB
        max-request-size: 5GB
    resources:
      static-locations: classpath:static/,file:static/

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置
    logic-delete-value: -1
    logic-not-delete-value: 0
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    #springboot 项目mybatis plus 设置 jdbcTypeForNull (oracle数据库需配置JdbcType.NULL, 默认是Other)
    jdbc-type-for-null: 'null'

aliyun:
  accessKeyId: ${ALIYUN_ACCESS_KEY_ID:}
  accessKeySecret: ${ALIYUN_ACCESS_KEY_SECRET:}

# 讯飞API配置
xfyun:
  appid: ${XFYUN_APPID:}
  api-key: ${XFYUN_API_KEY:}
  api-secret: ${XFYUN_API_SECRET:}
  api-password: ${XFYUN_API_PASSWORD:}
  model: lite

springdoc:
  default-flat-param-object: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true

agora:
  app:
    id: ${AGORA_APP_ID}       # 替换为你的声网App ID
    certificate: ${AGORA_CERTIFICATE}  # 替换为你的声网App证书
  token:
    expire-time: 3600           # Token有效期，单位秒（默认3600秒=1小时）

baidu:
  ai:
    app-id: ${BAIDU_APP_ID}
    api-key: ${BAIDU_API_KEY}
    secret-key: ${BAIDU_SECRET_KEY}
    group-id: edusys


